version: "2.0"

volumes:
  web_static:

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - "./db:/var/lib/postgresql/data/"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - production.env
    restart: unless-stopped
  web:
    image: nginx:1.19.6-alpine
    ports:
      - 3830:80
      - 3831:8081
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d:ro"
      - "web_static:/var/www/static:ro"
    restart: unless-stopped
    depends_on:
      - django
  django:
    build: .
    env_file:
      - production.env
    environment:
      - WWW_ROOT=/code
      - DB_HOST=db
      - DB_PORT=5432
      - PROMETHEUS_METRICS_EXPORT_PORT_RANGE=8001-8019
      - DJANGO_DEBUG=0
    ports:
      - "3851-3869:8001-8019"
    volumes:
      - "./user_upload:/code/user_upload"
      - "web_static:/code/static/"
      - "./vendor:/code/vendor"
    restart: unless-stopped
    depends_on:
      - db
